import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://dcvrjpbbybkasppgjiyh.supabase.co'
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || ''

const admin = createClient(supabaseUrl, serviceKey, {
  auth: { autoRefreshToken: false, persistSession: false },
})

const rawEvents = [
  {
    id: 'cal_zomerbar_2026',
    title: 'Zomerterras & Streekbierenbar',
    date: '2026-08-16',
    time: '14:00 - 20:00',
    location: 'Scoutslokalen Kriko-M, VP-Plein',
    description: 'Gezellige zomerbar op ons terras aan het lokaal! Kom proeven van heerlijke lokale streekbieren, verfrissende mocktails en versgebakken pannenkoeken. Iedereen van harte welkom!',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: true,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2025/08/528193945_1109483500529325_5681295269648299945_n-1024x403.jpg',
    facebook_event_url: 'https://www.facebook.com/ScoutsKrikoM',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_opfrisdag_2026',
    title: 'Lokaal Opfrisdag & Infostand',
    date: '2026-08-23',
    time: '10:00 - 17:00',
    location: 'Scoutslokalen Kriko-M',
    description: 'Samen steken we de handen uit de mouwen om ons terrein en de lokalen klaar te stomen voor het nieuwe scoutsjaar! Vanaf 15u is er een infostand voor nieuwe leden en ouders.',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: false,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2026/01/611180469_886620700982324_567087133102833330_n-1-819x1024.png',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_zomerslot_2026',
    title: 'Zomerfestijn & Kampvuur',
    date: '2026-08-30',
    time: '14:00 - 22:00',
    location: 'Scoutslokalen Kriko-M',
    description: 'Sluit de zomervakantie feestelijk af bij Scouts Kriko-M! Pleinspelen, springkasteel voor de jongste takken, givers-bar en een sfeervol avondkampvuur met gitaarmuziek.',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: true,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2025/06/GROEPSUITSTAP-2025-724x1024.png',
    document_url: 'https://www.kriko-m.be/wp-content/uploads/2024/11/Familiedag-2.pdf',
    external_link_url: 'https://forms.gle/Tbqk2BAku4zFQbrM9',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_bbq_2026',
    title: 'Kriko-M BBQ 2026 & KUBB-toernooi',
    date: '2026-09-19',
    time: '16:00 - 23:30',
    location: 'Scoutslokalen Kriko-M, VP-Plein',
    description: 'Kriko-M organiseert weer zijn jaarlijkse BBQ en we hebben jou daar heel graag bij! Om 16u start het spannende KUBB-toernooi (spelplezier voor jong en oud) en het speeldorp van de givers. Om 18u start de BBQ met aansluitend een gezellig kampvuur, leidingsactjes en feest met DJ Benny!',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: true,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2025/08/528193945_1109483500529325_5681295269648299945_n-1024x403.jpg',
    facebook_event_url: 'https://www.facebook.com/events/1109483500529325',
    facebook_post_url: 'https://www.facebook.com/ScoutsKrikoM/posts/1109483500529325',
    external_link_url: 'https://www.kriko-m.be/',
    document_url: 'https://www.kriko-m.be/wp-content/uploads/2025/08/528193945_1109483500529325_5681295269648299945_n.jpg',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_halloween_2026',
    title: 'Griezel Halloweentocht',
    date: '2026-10-31',
    time: '18:30 - 21:30',
    location: 'Scoutslokalen & Bos',
    description: 'Durf jij het aan? Een spannende avondwandeling vol griezelige verhalen, mysterieuze opdrachten en lekkere warme chocomelk na afloop bij het kampvuur.',
    audience: ['groep', 'welpen', 'jonggivers', 'givers'],
    is_evenement: false,
    facebook_event_url: 'https://www.facebook.com/ScoutsKrikoM',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_familiedag_2026',
    title: 'Familiedag & Herfstwandeling',
    date: '2026-11-15',
    time: '13:30 - 17:00',
    location: 'Natuurgebied Temse / Scoutslokalen',
    description: 'Zoals elk jaar trekken we er samen met de hele scoutsfamilie op uit! Een heerlijke herfstwandeling door de natuur met interactieve spelletjes en opdrachten onderweg. Trek dus zeker je warme jas, sjaal en muts aan! Na afloop verwarmen we ons met een heerlijke tas warme chocomelk of een streekbiertje.',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: true,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2025/11/Scherm%C2%ADafbeelding-2025-11-06-om-19.48.19-793x1024.png',
    facebook_event_url: 'https://www.facebook.com/ScoutsKrikoM',
    document_url: 'https://www.kriko-m.be/wp-content/uploads/2024/11/Familiedag-2.pdf',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_sint_2026',
    title: 'Sintvergadering & Snoepfeest',
    date: '2026-12-06',
    time: '14:00 - 17:00',
    location: 'Scoutslokalen Kriko-M',
    description: 'Hij komt, hij komt! Sinterklaas en zijn Zwarte Pieten brengen een bezoek aan onze lokalen. Breng je mooiste tekening mee en geniet van heerlijke speculaas en mandarines.',
    audience: ['groep', 'kapoenen', 'welpen'],
    is_evenement: false,
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_ouders_2027',
    title: 'Ouders in Leiding!',
    date: '2027-02-07',
    time: '14:00 - 17:00',
    location: 'Scoutslokalen Kriko-M',
    description: 'Op zondag 7 februari nemen de ouders het roer over! De leiding mag voor één keertje meespelen als lid, terwijl de enthousiaste ouders van de tak de vergadering leiden en fantastische spelletjes organiseren. Tot dan!',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: false,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2026/01/ouders-in-leiding-724x1024.png',
    facebook_post_url: 'https://www.facebook.com/ScoutsKrikoM',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_souphe_2027',
    title: 'Souphé 2027 (Nieuwjaarsdrink)',
    date: '2027-02-14',
    time: '12:00 - 16:00',
    location: 'VP-Plein & Scoutslokalen',
    description: 'Naar goede gewoonte zetten we het nieuwe jaar gezellig in met onze Souphé, olé! Heerlijke soep à volonté bereid door ouders en oud-leiding. Giverbar met drankjes en kleine versnaperingen. We verzamelen om 12u voor een halfuurtje pleinspelletjes en klinken vanaf 12u30 bij een knapperend vuurtje met een warm kopje soep (€2 à volonté, breng je eigen tas mee!).',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: true,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2026/01/611180469_886620700982324_567087133102833330_n-1-819x1024.png',
    facebook_event_url: 'https://www.facebook.com/ScoutsKrikoM',
    document_url: 'https://www.kriko-m.be/wp-content/uploads/2026/01/WIJ-ZOEKEN-NOG-SOEPMAKERS-819x1024.png',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_bidong_2027',
    title: 'Bidongfeesten 2027 (Ratatouille)',
    date: '2027-03-20',
    time: '18:00 - 03:00',
    location: 'Feestzaal & Scoutslokalen Kriko-M',
    description: 'De leiding en groepsleiding staan klaar met ons gezellig Ratatouille Eetfestijn! Van 18u tot 20u kan je genieten van Stoofvlees, Vol-au-vent of Vegetarisch stoofpotje met frietjes (€19 volw. / €15 kids). Om 20u volgt het dessertenbuffet & givers-bingo. Vanaf 21u sfeervolle buitenbar met streekbieren, en om 23u draaien de DJ\'s feestmuziek!',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: true,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2025/02/BIDONG-2025-1024x529.png',
    external_link_url: 'https://forms.gle/Tbqk2BAku4zFQbrM9',
    facebook_event_url: 'https://www.facebook.com/ScoutsKrikoM',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_districtsdag_2027',
    title: 'Districtsdag 2027',
    date: '2027-04-17',
    time: '13:00 - 18:00',
    location: 'Stropersbos & Scoutsterrein',
    description: 'Een supertoffe dag met alle scoutsgroepen uit het district! We bundelen onze krachten voor een massale bosgame en uitdagende opdrachten.',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: false,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2025/03/484537943_1191050235944560_5854147708910294240_n-875x1024.png',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_groepsuitstap_2027',
    title: 'Kriko-M Groepsuitstap',
    date: '2027-05-16',
    time: '09:00 - 18:00',
    location: 'Verzamelen aan het Station',
    description: 'Een spetterende daguitstap met alle takken samen! Verrassende bestemming en een onvergetelijke dag vol spel en avontuur.',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: true,
    banner_image: 'https://www.kriko-m.be/wp-content/uploads/2025/06/GROEPSUITSTAP-2025-724x1024.png',
    werkjaar: '2026-2027',
  },
  {
    id: 'cal_kampvoorstelling_2027',
    title: 'Kampvoorstelling Ouders',
    date: '2027-06-23',
    time: '18:30 - 21:00',
    location: 'Scoutslokalen Kriko-M, VP-Plein',
    description: 'Kampvoorstelling voor ouders op het lokaal. Jullie krijgen hier alle kampuitnodigingen, praktische info en de kamplocaties uitgelegd! Uren per tak: Kapoenen 18u30, Welpen 19u00, Jonggivers 19u30, Givers 20u00. (Gelieve de info nog even geheim te houden voor de leden!).',
    audience: ['groep', 'kapoenen', 'welpen', 'jonggivers', 'givers'],
    is_evenement: false,
    werkjaar: '2026-2027',
  },
]

const sanitizedEvents = rawEvents.map(e => ({
  id: e.id,
  title: e.title,
  date: e.date,
  time: e.time || '',
  location: e.location || '',
  description: e.description || '',
  audience: e.audience || ['groep'],
  is_evenement: !!e.is_evenement,
  datum_tot: null,
  banner_image: e.banner_image || '',
  facebook_event_url: e.facebook_event_url || '',
  facebook_post_url: e.facebook_post_url || '',
  external_link_url: e.external_link_url || '',
  document_url: e.document_url || '',
  werkjaar: e.werkjaar || '2026-2027',
}))

async function seed() {
  console.log('Seeding calendar events to Supabase...')
  const { error } = await admin.from('calendar').upsert(sanitizedEvents)
  if (error) {
    console.error('Error seeding calendar:', error)
  } else {
    console.log('Successfully seeded', sanitizedEvents.length, 'real events into calendar including August 2026!')
  }
}

seed()
